/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutoriaRouteImport } from './routes/tutoria'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as ComparativosRouteImport } from './routes/comparativos'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurmasIndexRouteImport } from './routes/turmas.index'
import { Route as TurmasTurmaIdRouteImport } from './routes/turmas.$turmaId'

const TutoriaRoute = TutoriaRouteImport.update({
  id: '/tutoria',
  path: '/tutoria',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativosRoute = ComparativosRouteImport.update({
  id: '/comparativos',
  path: '/comparativos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasIndexRoute = TurmasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TurmasRoute,
} as any)
const TurmasTurmaIdRoute = TurmasTurmaIdRouteImport.update({
  id: '/$turmaId',
  path: '/$turmaId',
  getParentRoute: () => TurmasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/comparativos': typeof ComparativosRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/turmas': typeof TurmasRouteWithChildren
  '/tutoria': typeof TutoriaRoute
  '/turmas/$turmaId': typeof TurmasTurmaIdRoute
  '/turmas/': typeof TurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/comparativos': typeof ComparativosRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/tutoria': typeof TutoriaRoute
  '/turmas/$turmaId': typeof TurmasTurmaIdRoute
  '/turmas': typeof TurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/comparativos': typeof ComparativosRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/turmas': typeof TurmasRouteWithChildren
  '/tutoria': typeof TutoriaRoute
  '/turmas/$turmaId': typeof TurmasTurmaIdRoute
  '/turmas/': typeof TurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/comparativos'
    | '/importar'
    | '/login'
    | '/notas'
    | '/turmas'
    | '/tutoria'
    | '/turmas/$turmaId'
    | '/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/comparativos'
    | '/importar'
    | '/login'
    | '/notas'
    | '/tutoria'
    | '/turmas/$turmaId'
    | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/comparativos'
    | '/importar'
    | '/login'
    | '/notas'
    | '/turmas'
    | '/tutoria'
    | '/turmas/$turmaId'
    | '/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  ComparativosRoute: typeof ComparativosRoute
  ImportarRoute: typeof ImportarRoute
  LoginRoute: typeof LoginRoute
  NotasRoute: typeof NotasRoute
  TurmasRoute: typeof TurmasRouteWithChildren
  TutoriaRoute: typeof TutoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutoria': {
      id: '/tutoria'
      path: '/tutoria'
      fullPath: '/tutoria'
      preLoaderRoute: typeof TutoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativos': {
      id: '/comparativos'
      path: '/comparativos'
      fullPath: '/comparativos'
      preLoaderRoute: typeof ComparativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas/': {
      id: '/turmas/'
      path: '/'
      fullPath: '/turmas/'
      preLoaderRoute: typeof TurmasIndexRouteImport
      parentRoute: typeof TurmasRoute
    }
    '/turmas/$turmaId': {
      id: '/turmas/$turmaId'
      path: '/$turmaId'
      fullPath: '/turmas/$turmaId'
      preLoaderRoute: typeof TurmasTurmaIdRouteImport
      parentRoute: typeof TurmasRoute
    }
  }
}

interface TurmasRouteChildren {
  TurmasTurmaIdRoute: typeof TurmasTurmaIdRoute
  TurmasIndexRoute: typeof TurmasIndexRoute
}

const TurmasRouteChildren: TurmasRouteChildren = {
  TurmasTurmaIdRoute: TurmasTurmaIdRoute,
  TurmasIndexRoute: TurmasIndexRoute,
}

const TurmasRouteWithChildren =
  TurmasRoute._addFileChildren(TurmasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  ComparativosRoute: ComparativosRoute,
  ImportarRoute: ImportarRoute,
  LoginRoute: LoginRoute,
  NotasRoute: NotasRoute,
  TurmasRoute: TurmasRouteWithChildren,
  TutoriaRoute: TutoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
