namespace ProjetoVarejo.Application.Contracts.Services.DTOs;

/// <summary>
/// DTO for daily sales report item.
/// </summary>
public class VendaDiariaItem
{
    /// <summary>
    /// Date of the sales.
    /// </summary>
    public DateTime Data { get; set; }

    /// <summary>
    /// Alias for Data property (for UI compatibility).
    /// </summary>
    public DateTime Dia => Data;

    /// <summary>
    /// Total number of sales on this date.
    /// </summary>
    public int Quantidade { get; set; }

    /// <summary>
    /// Total revenue on this date.
    /// </summary>
    public decimal Total { get; set; }
}

/// <summary>
/// DTO for sales by payment method report item.
/// </summary>
public class VendaPorFormaItem
{
    /// <summary>
    /// Payment method type.
    /// </summary>
    public string Forma { get; set; } = string.Empty;

    /// <summary>
    /// Total quantity of sales using this payment method.
    /// </summary>
    public int Quantidade { get; set; }

    /// <summary>
    /// Alias for Quantidade (for UI compatibility).
    /// </summary>
    public int Qtd => Quantidade;

    /// <summary>
    /// Total revenue from this payment method.
    /// </summary>
    public decimal Total { get; set; }

    /// <summary>
    /// Percentage of total sales from this payment method.
    /// </summary>
    public decimal Percentual { get; set; }
}

/// <summary>
/// DTO for sales by salesperson report item.
/// </summary>
public class VendaPorVendedorItem
{
    /// <summary>
    /// Salesperson ID.
    /// </summary>
    public int UsuarioId { get; set; }

    /// <summary>
    /// Salesperson name.
    /// </summary>
    public string NomeVendedor { get; set; } = string.Empty;

    /// <summary>
    /// Alias for NomeVendedor (for UI compatibility).
    /// </summary>
    public string Vendedor => NomeVendedor;

    /// <summary>
    /// Total number of sales by this salesperson.
    /// </summary>
    public int QuantidadeVendas { get; set; }

    /// <summary>
    /// Alias for QuantidadeVendas (for UI compatibility).
    /// </summary>
    public int QtdVendas => QuantidadeVendas;

    /// <summary>
    /// Total revenue generated by this salesperson.
    /// </summary>
    public decimal TotalVendas { get; set; }

    /// <summary>
    /// Alias for TotalVendas (for UI compatibility).
    /// </summary>
    public decimal Total => TotalVendas;

    /// <summary>
    /// Average ticket value (total sales / number of sales).
    /// </summary>
    public decimal TicketMedio { get; set; }
}

/// <summary>
/// DTO for product ranking report item (used in ABC Curve and Top Products).
/// </summary>
public class ProdutoRankingItem
{
    /// <summary>
    /// Product ID.
    /// </summary>
    public int ProdutoId { get; set; }

    /// <summary>
    /// Product code.
    /// </summary>
    public string Codigo { get; set; } = string.Empty;

    /// <summary>
    /// Product description.
    /// </summary>
    public string Descricao { get; set; } = string.Empty;

    /// <summary>
    /// Total quantity sold.
    /// </summary>
    public decimal QuantidadeVendida { get; set; }

    /// <summary>
    /// Alias for QuantidadeVendida (for UI compatibility).
    /// </summary>
    public decimal Quantidade => QuantidadeVendida;

    /// <summary>
    /// Total revenue from this product.
    /// </summary>
    public decimal TotalVendido { get; set; }

    /// <summary>
    /// Alias for TotalVendido (for UI compatibility).
    /// </summary>
    public decimal Faturamento => TotalVendido;

    /// <summary>
    /// Percentage of total revenue (for ranking/ABC analysis).
    /// </summary>
    public decimal Percentual { get; set; }

    /// <summary>
    /// ABC classification (A, B, or C) for curve analysis.
    /// </summary>
    public string? ClassificacaoAbc { get; set; }

    /// <summary>
    /// Alias for ClassificacaoAbc (for UI compatibility).
    /// </summary>
    public string? Classe => ClassificacaoAbc;
}

/// <summary>
/// DTO for cash flow analysis report item.
/// </summary>
public class FluxoCaixaItem
{
    /// <summary>
    /// Date of the cash flow entry.
    /// </summary>
    public DateTime Data { get; set; }

    /// <summary>
    /// Alias for Data (for UI compatibility).
    /// </summary>
    public DateTime Dia => Data;

    /// <summary>
    /// Total cash inflows (sales + supplies).
    /// </summary>
    public decimal Entradas { get; set; }

    /// <summary>
    /// Total cash outflows (withdrawals).
    /// </summary>
    public decimal Saidas { get; set; }

    /// <summary>
    /// Net cash flow (inflows - outflows).
    /// </summary>
    public decimal Liquido { get; set; }

    /// <summary>
    /// Cumulative balance up to this date.
    /// </summary>
    public decimal SaldoAcumulado { get; set; }

    /// <summary>
    /// Alias for SaldoAcumulado (for UI compatibility).
    /// </summary>
    public decimal Saldo => SaldoAcumulado;
}
